#!/bin/bash
echo We can add more module loading in this script
module load python/3.8.2
module load git/2.22.0
module load abyss/2.2.0
module load blast+/2.10.1
module load sepp/4.3.10
module load augustus/3.3.2
module load hmmer/3.3
module load busco/4.1.0